//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSpacesTools.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSpacesTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DJ_miXxXer.
        /// </summary>
        internal static string AppAuthor {
            get {
                return ResourceManager.GetString("AppAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на iSpacesTools Alpha.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запуск недоступен.
        /// </summary>
        internal static string ButtonPluginRunDisabed {
            get {
                return ResourceManager.GetString("ButtonPluginRunDisabed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запустить.
        /// </summary>
        internal static string ButtonPluginRunEnabled {
            get {
                return ResourceManager.GetString("ButtonPluginRunEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (загрузка).
        /// </summary>
        internal static string Common_LoadingBraces {
            get {
                return ResourceManager.GetString("Common_LoadingBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Критическая ошибка приложения.
        /// </summary>
        internal static string ErrorCriticalGlobalHeader {
            get {
                return ResourceManager.GetString("ErrorCriticalGlobalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложение было внезапно закрыто. Информация:.
        /// </summary>
        internal static string ErrorCriticalGlobalMessage {
            get {
                return ResourceManager.GetString("ErrorCriticalGlobalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены?.
        /// </summary>
        internal static string ModalTitleYouSure {
            get {
                return ResourceManager.GetString("ModalTitleYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти на сайт автора?.
        /// </summary>
        internal static string PlguinAuthorLinkConfirm {
            get {
                return ResourceManager.GetString("PlguinAuthorLinkConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сайт автора.
        /// </summary>
        internal static string PluginAuthorLink {
            get {
                return ResourceManager.GetString("PluginAuthorLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анонимный доступ.
        /// </summary>
        internal static string SessionAnonymousLogin {
            get {
                return ResourceManager.GetString("SessionAnonymousLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректная.
        /// </summary>
        internal static string SessionStateInvalid {
            get {
                return ResourceManager.GetString("SessionStateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анонимный доступ.
        /// </summary>
        internal static string SessionStatusAnonymous {
            get {
                return ResourceManager.GetString("SessionStatusAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не установлен.
        /// </summary>
        internal static string SessionStatusEmpty {
            get {
                return ResourceManager.GetString("SessionStatusEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверенная.
        /// </summary>
        internal static string SessionStatusValid {
            get {
                return ResourceManager.GetString("SessionStatusValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (неизвестно).
        /// </summary>
        internal static string UnknownValue {
            get {
                return ResourceManager.GetString("UnknownValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на v.
        /// </summary>
        internal static string VersionShort {
            get {
                return ResourceManager.GetString("VersionShort", resourceCulture);
            }
        }
    }
}
